mail/urls.py
from django.urls import path

from . import views

app_name='mail'
urlpatterns = [
    path('', views.index, name='index'),
    path('customers/', views.CustomerListView.as_view(), name='customers'),
    path('customers/<str:pk>/', views.CustomerDetailView.as_view(), name='customer_detail'),
    path('send/', views.send_mail, name='send'),
    path('settings/', views.settings, name='settings'),
    path('settings/<int:setting_id>/delete', views.delete_setting, name='delete_setting'),
    path('<uuid:promotion_uuid>/', views.check_open, name='check_open'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mail/', include('mail.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Mail service</title>

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
  <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">

</head>
<body>
  {% include 'includes/navbar.html' %}
  {% block content %}
  {% endblock %}
</body>
</html>

templates/includes/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}


{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

templates/includes/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'mail:index' %}">Mailer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mail:send' %}">Mail service</a>
      </li>
    </ul>
  </div>
  <span class="navbar-text">
    {% if user.is_authenticated %}
      Logged as {{ user.username }}
      <a href="{% url 'logout' %}" class="btn btn-warning" >Logout</a>
    {% else %}
      <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-warning">Google 로그인</a>
      <a href="{% url 'social:begin' 'naver' %}" class="btn btn-success">Naver 로그인</a>
    {% endif %}
  </span>
</nav>

templates/warning.html
{% extends 'base.html' %}

{% block content %}
  <h2>잘못된 접근입니다</h2>
{% endblock %}